### ISSUE TITLE
Feature request: login as selected user.

### ISSUE THREAD

**Issue by seler** [RevSquare/gipsy#5]
I'd love to have feature where I can login as selected user. It should only be available to superusers or users with explicit permission.

**Comment by omji** [comment]
I am not sure I understand, what do you call a selected user and what specific features should he have?

**Comment by seler** [comment]
What I mean is to be able to log in as other user wihout knowing his password etc. 
Flow would go like that:
1. I log into admin.
2. I go to changelist page /admin/auth/user/ 
3. I click on user to go to changeform page
4. On changeform page i click on button "Log is as selected user"
5. App takes me to project homepage. Now i'm logged in as user i selected and not as user i was logged in when i clicked this button :)

**Comment by omji** [comment]
I see, but I am affraid ther eis a bit of a security concern here. What if, for exemple, this lib is installed on a ecommerce platform with saved payment facilities? I know that a superadmin can change password to take control over a client account, but at least we have logs of which account did so, which accoutns were impacted by this account and when?

**Comment by omji** [comment]
I see your point though and its a very good idea for debugging. But I would put it on another lib that is independant from this one.

**Comment by seler** [comment]
Ok.

**Comment by omji** [comment]
Closing and lets think about this lib :-)
